### ISSUE TITLE
Wolves' model won't render

### ISSUE THREAD

**Issue by rja530** [JayZX535/wildcraft#13] opened 2018-04-09 21:33 UTC
I logged on and could not see any of my wolves. They're still there. I can interact with them and see their shadows, but their models are not. I tried it on a new world and spawning in more wolves, but neither worked. It could be another mod conflict, so I will test that, but I don't really know. 
 This is my favorite mod now, and really want to play with my dogs.

**Comment by JayZX535** [comment] 2018-04-10 00:20
Hmmm, that's not good.  What version is this?  Can you please post your log file?

And if anyone else is testing this, please post version/log files here as well.

**Comment by rja530** [comment] 2018-04-10 00:44
The version is 1.12.2 with forge 14.23.0.2515

I attached the file. If it isn't there I can try again. Sorry if it doesn't work, I am new to the whole logs and file thing

**Comment by JayZX535** [comment] 2018-04-10 01:16
I can't seem to access the log file-- could you send it to me at wildcraftmc2017@gmail.com ?  Thanks!

**Comment by JayZX535** [comment] 2018-04-10 19:04
This appears to be a possible incompatibility with Optifine and its random mob skins feature-- I can't seem to reproduce it.  Anyone else able to test and replicate this bug?

**Comment by JayZX535** [comment] 2018-04-13 04:50
Confirmed to be a bug with Optifine, but seems to be happening with other mods too... needs more testing.

**SOLUTION FOR OPTIFINE USERS:** Disable the "random mob skins" option, as it changes the way Minecraft renders mobs (thus making it incompatible with WC)

**Comment by JayZX535** [comment] 2018-05-06 16:50
Closing issue for now, will re-open if other mods cause the same problem.

**Closed as completed by JayZX535** 2018-05-06 16:50 UTC
Labels: wontfix, troubleshooting, for reference
